#!/bin/bash
# Titulo:       practicas1-4
# Fecha:        21/3/2020
# Autor:        David Muñoz Sánchez
# Versión:      1.0
# Descripción:  Guiones para las prácticas de repaso 1 - 4
# Opciones:     Ninguna
# Uso:          

man find | head -15 >> /home/davidms_83/repaso/prueba2/arch1.txt
