#!/bin/bash
# Titulo:       practicas1-4
# Fecha:        21/3/2020
# Autor:        David Muñoz Sánchez
# Versión:      1.0
# Descripción:  Guiones para las prácticas de repaso 1 - 4
# Opciones:     Ninguna
# Uso:          

echo $[2+3+4+5/2] && echo 2+3+4+5/2|bc -l
