#!/bin/bash
# Practica 6, depuración de errores
# Autor: David Muñoz Sánchez

# 1. Usa uno de los guiones que tienes y ejecútalo en background
# Para este ejercicio, haré uso del guión de la práctica 5
.//Desktop/PRACTICA5 &

# 2. Indica el número de proceso asignado
# Como se puede obsevar en la captura que he adjuntado, el número de proceso
# asignado es 1872

# 3. ¿Cómo matarías a dicho proceso antes de finalizar?
# Lo mataría usando la siguiente orden:
kill 1872

# 4. Muestra la información más completa de todos los procesos que se están ejecutando en el sistema 
# (no solo los tuyos)
ps -e


